### ISSUE TITLE
When using the `git commit` command (without -m and a commit message), it will fail

### ISSUE THREAD

**Issue by gbaian10** [ljnsn/cz-conventional-gitmoji#208] opened 2024-09-25 04:33 UTC
When using the git commit command (without -m and a commit message), git will open an editor for you to enter the commit message. 

In this mode, cz-conventional-gitmoji won't add emojis for you, and if you don't manually add them, the commit will never succeed.

**Comment by ljnsn** [comment] 2024-09-27 11:54
Thanks for the report, I'll take a look.

**Comment by gbaian10** [comment] 2024-09-27 16:14
@ljnsn 
I have a very rough solution for this issue and the merge problem with #166 .
I believe it can definitely be improved. If needed, I can post the code here. I really like this repo and hope it can get better!

**Comment by gbaian10** [comment] 2024-09-27 18:36
> When using the git commit command (without -m and a commit message), git will open an editor for you to enter the commit message.
> 
> In this mode, cz-conventional-gitmoji won't add emojis for you, and if you don't manually add them, the commit will never succeed.

I later discovered that this seems to be an error caused by `re.match` not matching, possibly due to a missing newline character?

**Comment by ljnsn** [comment] 2024-10-03 06:51
@gbaian10 I cannot reproduce this, could you please post a series of commands that's not working for you?

When you commit with just `git commit` without specifying a message, git indeed opens an editor, as usual. However, `cz-gitmoji` will still do its job and process the commit message properly (as long as it matches conventional-gitmoji pattern).

**Comment by gbaian10** [comment] 2024-10-03 07:19
@ljnsn 

1. When your commit message contains only a single line with "Commit summary" and lacks a newline at the end, the commit will fail to match.
![image](https://github.com/user-attachments/assets/0d35d2a1-9e83-4bb3-a319-4d52825c00c7)


2. When your commit message includes both a "Commit summary" and a "Description," missing a newline between them will also cause the commit to fail to match.
![image](https://github.com/user-attachments/assets/f097e61f-bb7d-4db4-9df0-d3fe26232aa0)

---

For situation 2, requiring a newline is reasonable, but for situation 1, it's common not to have an extra newline. 
For instance, when merging branches, the auto-generated messages by Git also don't include this newline.

**Comment by ljnsn** [comment] 2024-10-03 07:21
Thanks! I'll check further.

**Comment by gbaian10** [comment] 2024-10-03 07:21
My current solution is to always add an extra `\n` after the first line, which ensures it always passes.
Even if there's an extra `\n`, Git seems to ignore it when reading the Description block.

**Comment by gbaian10** [comment] 2024-10-03 07:26
> @ljnsn I have a very rough solution for this issue and the merge problem with #166 . I believe it can definitely be improved. If needed, I can post the code here. I really like this repo and hope it can get better!

For merge, it first opens the `.git/MERGE_MSG` file. I read the text from this file and add "merge: " at the beginning, ensuring it always matches and adds an emoji.
However, when a merge conflict occurs, I have to go through the commit process again.

**Comment by ljnsn** [comment] 2024-10-03 07:30
I think for #166 we need to read the `allowed_prefixes`, don't really want to introduce another dirty solution.

If you have a fix for this newline problem, I'd be happy to look at a PR though.

**Comment by gbaian10** [comment] 2024-10-03 07:35
This is my current dirty solution.

```py
def insert_newline(text: str) -> str:
    """Insert an additional '\n' at the first occurrence of '\n'.

    Currently, if a merge commit contains a description and there is no '\n\n' to separate it from the summary,
    it will cause the regex to fail to match and result in an error.
    Moreover, if there are already double newlines, inserting an additional newline will have no impact.
    """
    index = text.find("\n")
    if index != -1:
        text = text[: index + 1] + "\n" + text[index + 1 :]
    return text


def my_fix_merge_commit(filepath: Path, msg: str) -> str:
    """This code was added to fix issues with commit messages that occur during merges."""
    msg = insert_newline(msg)
    merge_header = "merge: "
    absolute_filepath = filepath.resolve()
    if absolute_filepath == Path(".git/MERGE_MSG").resolve():
        return msg if msg.startswith(merge_header) else merge_header + msg
    if absolute_filepath == Path(".git/COMMIT_EDITMSG").resolve():
        return msg if not msg.startswith("Merge ") else merge_header + msg
    return msg


def run() -> int:
    """The pre-commit hook that modifies the commit message."""
    args = get_args()
    if args.commit_msg_file:
        filepath = Path(args.commit_msg_file)
        # TODO: commit message file encoding can be set via git config
        # key 'i18n.commitEncoding' and defaults to UTF-8, get encoding
        # from there.
        msg = filepath.read_text(encoding=UTF8)

        # This is the part I added to fix the merge commit issue.
        msg = my_fix_merge_commit(filepath, msg)

        with filepath.open("w", encoding=UTF8) as f:
            f.write(gitmojify(msg))
    else:
        msg = args.message
        sys.stdout.write(gitmojify(msg))
    return 0
```

Regarding allowed_prefixes, sorry, I haven't studied the commitizen code yet.

**Comment by gbaian10** [comment] 2024-10-03 07:37
> I think for #166 we need to read the `allowed_prefixes`, don't really want to introduce another dirty solution.
> 
> If you have a fix for this newline problem, I'd be happy to look at a PR though.

Using `allowed_prefixes` might mean that automatic merges won't have emojis? But I really like the emoji design.

If it's not used in CI, it could even immediately differentiate between local merges and remote merges (one with emoji, the other without).

**Comment by ljnsn** [comment] 2024-10-12 22:50
@gbaian10 this should be fixed now, let me know if you still encounter issues.

**Closed by ljnsn** 2024-10-12 22:50 UTC

**Comment by gbaian10** [comment] 2024-10-13 06:35
@ljnsn 
When I use the `convert_prefixes` mentioned in [this comment](https://github.com/ljnsn/cz-conventional-gitmoji/issues/166#issuecomment-2408081558).

`Commit Description` is incorrectly merged into the `Commit Summary`, becoming a single-line Commit Summary.

Input:
![image](https://github.com/user-attachments/assets/b3235579-0efe-411a-ae44-62c0f6f46063)

Output:
![image](https://github.com/user-attachments/assets/5f84441e-f0db-40e2-bef4-d5fca156d8e8)

Expected:
![image](https://github.com/user-attachments/assets/7b47cfd9-05d7-48c0-9300-2a3e1bc9a1cf)
