### ISSUE TITLE
BUG: gitmojify hook not prepending the commit on Windows

### ISSUE THREAD

**Issue by jjfantini** [ljnsn/cz-conventional-gitmoji#120] opened 2024-01-23 18:05 UTC
I am looking to use the commit hook to append emojis onto my commit messages, although it doesn't seem to be working?

```
# pyproject.toml

[tool.commitizen]
name = "cz_gitmoji"
version = "0.0.0"
tag_format = "v$version"
update_changelog_on_bump = true
annotated_tag = true
major_version_zero = true
version_files = [
    "pyproject.toml:^version",
]
path = ".cz-config.js"

==================================

#.pre-commit-config.yaml

repos:
  - repo: https://github.com/ljnsn/cz-conventional-gitmoji
    rev: main
    hooks:
      - id: conventional-gitmoji

```

**Comment by ljnsn** [comment] 2024-01-23 20:44
Did you install the commit message pre-commit hooks with `pre-commit install --hook-type commit-msg`?

**Comment by jjfantini** [comment] 2024-01-23 20:46
Yes I have because I am using a commitizen hook as well that uses commit-msg

sent from humblWorkshop

---------------------------------------------
⬇️⬇️ TRY OUR DATA TOOLS ⬇️⬇️
📈📊humblfinance.io📊📈

⬇️⬇️ JOIN OUR SMALL COMMUNITY ⬇️⬇️
 📓📖humblblog.com📖📓
---------------------------------------------
⬇️⬇️ CONTACT ⬇️⬇️
📧: ***@***.***
📧: ***@***.***
📱: +1 (307) 278-6561

**Comment by ljnsn** [comment] 2024-01-23 21:33
Your config looks fine. Could you make a minimal reproducible example repo or describe exactly your workflow?

This works for example:

```bash
poetry new foo
cd foo
git init
poetry add pre-commit
# add your cz config to pyproject.toml
# add your pre-commit config
pre-commit install --install-hooks  --hook-type commit-msg
git add .
git commit -m "init: initial version"
# commit message: 🎉 init: initial commit
```

**Comment by jjfantini** [comment] 2024-01-24 12:25
Yes, I am working in this [repo](https://github.com/jjfantini/gitmoji-test). Feel free to take a look! Again, I  really appreciate the help

**Comment by jjfantini** [comment] 2024-01-24 12:32
I have tried doing what you suggested:

```
Command failed with exit code 1: git commit -m "feat: test"
gitmojify................................................................Failed
- hook id: conventional-gitmoji
- exit code: 1

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\jjfan\.cache\pre-commit\repo_zkw_ns5\py_env-python3\Scripts\gitmojify.EXE\__main__.py", line 7, in <module>
  File "C:\Users\jjfan\.cache\pre-commit\repo_zkw_ns5\py_env-python3\Lib\site-packages\gitmojify\mojify.py", line 57, in run
    f.write(gitmojify(msg))
  File "C:\Users\jjfan\github\gitmoji-test\menv\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\u2728' in position 0: character maps to <undefined>

```

**Comment by ljnsn** [comment] 2024-01-24 17:41
> After running pre-commit install, my hooks get messed up and ruff executable can't be found

The ruff executable missing is something else, for me your repo works just fine (after adding the config you posted above to pre-commit-config, it doesn't seem to be there on the dev/gitmojify branch).

The issue seems to be that windows on writing the file uses latin1 encoding and thus cannot encode the unicode character that is assigned to the gitmoji. Do you get the same error if you run `gitmojify -m "fix: foo"` on cli?

I'll try to reproduce this and make a fix.

**Closed** 2024-01-24 22:42 UTC

**Comment by ljnsn** [comment] 2024-01-24 23:01
@jjfantini can you check if this is fixed for you if not I'll reopen this

**Comment by jjfantini** [comment] 2024-01-25 21:21
Still not woring, have tried to get it working. Not getting any errors, but not seeing the emoji in the repo?

**Comment by jjfantini** [comment] 2024-01-25 21:32
It seems to be working when using the text input as writing my own custom commit.

So, 

CLI looks to be working and bumping
Message bar in VSCode/ CURsor is working

will check more tmrw...

**Comment by jjfantini** [comment] 2024-01-26 11:55
Should I try a local pre-commit-config.yaml instead of using your repo?
